### PR TITLE
Remove DS_Store and add to gitignore

### PR DESCRIPTION
**Pull request by kid-icarus**
This removes .DS_Store from the root directory of the project, and adds it to .gitignore, such that the file will no longer be under version control.

### CODE REVIEW

**Comment by operatorjen** [comment]
LOOK RYANBRO IS BEING HELPFUL ON A SUNDAY NIGHT

**Comment by llkats** [comment]
Please add description and re-submit.

**Comment by operatorjen** [comment]
ooh she schooled you in the :balloon: :balloon:

**Comment by TehShrike** [comment]
lol

**Comment by operatorjen** [comment]
REBASE COMMITS PLS

**Comment by tarmstrong** [comment]
Please finish commit messages with a period or an exclamation mark.

**Comment by TehShrike** [comment]
?like this

**Comment by chee** [comment]
needs tests

**Pull request merged**
